# Project information
site_name: OpenStudyBuilder
site_author: Katja Gla√ü
site_description: This is a community site containing information about the OpenStudyBuilder Application. The OpenStudyBuilder is an open-source project for clinical study evaluations. This tool is a new approach for working with studies that once fully implemented will drive end-to-end consistency and more efficient processes.

# Copyright
copyright: Copyright &copy; 2022 OpenStudyBuilder Project

nav:
  - Description: index.md
  - Info: 
    - Status: status.md
    - Events: info_events.md
    - Past Events: info_events_past.md
    - DDF Vision: info_ddf_vision.md
    - DDF Context: info_ddf.md
    - Environments: info_environment.md
    - Costs: info_costs.md
    - Integrations: info_integrations.md
    - Resources: info_resources.md
    - Newsletter: info_newsletter.md
  - Guides:
    - Introduction: guide_intro.md
    - Overview: guide_overview.md
    - Environments: guide_sandbox.md
    - Codelists: guide_codelists.md
    - CRF: guide_crf.md
    - Manage studies: guide_manage_studies.md
    - Study Structure: guide_study_structure.md
    - Visits: guide_visits.md
    - Activity Concept: guide_activity_concept.md
    - Activity Dashboard: guide_bc_dashboard.md
    - API: guide_api.md
  - FAQ:
    - faq.md

# Style Sheet
extra_css:
  - stylesheets/general.css

# Repository
repo_name: OpenStudyBuilder
repo_url: https://gitlab.com/Novo-Nordisk/nn-public/openstudybuilder/project-description

# Configuration
theme:
  name: material

  features:
    - navigation.tabs
    - navigation.indexes
  favicon: img/favicon.ico
  icon:
    logo: logo
  font:
    text: Roboto
    code: Roboto Mono
  custom_dir: mkdocs_custom/

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.snippets:
      base_path: .
  - attr_list